### ISSUE TITLE
Google app engine cannot access key

### ISSUE THREAD

**Issue by paullj1** [google/identity-toolkit-python-client#17]
```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/s~appname/1.391345578538984665/run.py", line 6, in <module>
    import application
  File "/base/data/home/apps/s~appname/1.391345578538984665/application/__init__.py", line 32, in <module>
    app.config.from_object('application.settings.Production')
  File "/base/data/home/apps/s~appname/1.391345578538984665/lib/flask/config.py", line 162, in from_object
    obj = import_string(obj)
  File "/base/data/home/apps/s~appname/1.391345578538984665/lib/werkzeug/utils.py", line 417, in import_string
    return getattr(__import__(module, None, None, [obj]), obj)
  File "/base/data/home/apps/s~appname/1.391345578538984665/application/settings.py", line 14, in <module>
    class Config(object):
  File "/base/data/home/apps/s~appname/1.391345578538984665/application/settings.py", line 40, in Config
    server_config_json)
  File "/base/data/home/apps/s~appname/1.391345578538984665/lib/identitytoolkit/gitkitclient.py", line 234, in FromConfigFile
    key_file = open(json_data['serviceAccountPrivateKeyFile'], 'rb')
IOError: [Errno 2] No such file or directory: u'./google_key.json'
```

**Comment by Alevale** [comment]
i just had this issue a couple of days ago.
my structure is the following 

```
/backend
    -mypythonfile
/config
    -gitkit-server-config.json
    -oauthkeyfile.p12
/frontend
```

``` python
server_config_json = path.realpath(path.join('config', 'gitkit-server-config.json'))

json_data = simplejson.load(open(server_config_json))

key_file = open(path.realpath(path.join('config', 'oauthkeyfile.p12')))
key = key_file.read()
key_file.close()

clientId = json_data.get('clientId')
projectId = json_data.get('projectId')
if not clientId and not projectId:
  raise Exception('Missing projectId or clientId in server configuration.')

gitkit_instance = gitkitclient.GitkitClient(
    clientId,
    json_data['serviceAccountEmail'],
    key,
    json_data['widgetUrl'],
    json_data['cookieName'],
    None,
    projectId)
```

this is the only workaround that i found till this moment, will update the FromConfigFile method so that it allows some path directive
