### ISSUE TITLE
base64 decode error with unicode password hash

### ISSUE THREAD

**Issue by rogeremasse** [google/identity-toolkit-python-client#18]
I get the follow traceback consistently when attempting to log in with a "password account":

base64.urlsafe_b64decode works if you str() it's arg but fails with a unicode arg on line 81.

ERROR    2016-03-19 20:27:29,864 base.py:223] gitkit_instance.GetUserById("07250307095831458805DA000527416E2C4F6C611400"):
Traceback (most recent call last):
  File "/Users/rmasse/google-app-engine/laruta-1031/default/bp_content/themes/macpa/handlers/base.py", line 221, in _authorize
    gitkit_user_data = main.gitkit_instance.GetUserById(gitkit_user.user_id)
  File "/Users/rmasse/google-app-engine/laruta-1031/default/lib/identitytoolkit/gitkitclient.py", line 296, in GetUserById
    return GitkitUser.FromApiResponse(user)
  File "/Users/rmasse/google-app-engine/laruta-1031/default/lib/identitytoolkit/gitkitclient.py", line 104, in FromApiResponse
    return cls(**response)
  File "/Users/rmasse/google-app-engine/laruta-1031/default/lib/identitytoolkit/gitkitclient.py", line 81, in __init__
    self.password_hash = base64.urlsafe_b64decode(kwargs['passwordHash'])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/base64.py", line 116, in urlsafe_b64decode
    return b64decode(s.translate(_urlsafe_decode_translation))
TypeError: character mapping must return integer, None or unicode

**Comment by fernandonm** [comment]
Is there anybody working to fix this?
